# Generated by Django 5.2 on 2025-05-03 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postmodel'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='likemodel',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='postmodel',
            index=models.Index(fields=['owner'], name='posts_postm_owner_i_cda5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='postmodel',
            index=models.Index(fields=['-created_at'], name='posts_postm_created_eeda90_idx'),
        ),
    ]
