services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_twitter_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER = 'redis://redis:6379/0'
      - CELERY_BACKEND = 'redis://redis:6379/0'
    depends_on:
      - redis
    env_file:
      - .env

  celery:
    build: .
    container_name: celery
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    environment:
      - REDIS_HOST=redis

volumes:
  redis_data:
