services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mini_twitter_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_twitter_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER = 'redis://redis:6379/0'
      - CELERY_BACKEND = 'redis://redis:6379/0'
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - mini_twitter_network

  celery:
    build: .
    container_name: celery
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    environment:
      - REDIS_HOST=redis
    networks:
      - mini_twitter_network
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mini_twitter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mini_twitter_network

volumes:
  redis_data:
  postgres_data:

networks:
  mini_twitter_network:
    driver: bridge
